apiVersion: v1
kind: ReplicationController
metadata:
  name: backend-replicationcontroller
  namespace: temperature
spec:
  replicas: 3
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        env:
        - name: DATABASE_URI
          value: postgres://netcracker:111@postgresql.postgresql/netcracker
        image: eatmygunzoldier/temperature:v9
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      restartPolicy: Always

